### PR TITLE
flash messages for bad zip or no opps

### PR DESCRIPTION
**Pull request by AdamD-2096**
in the middle of prepping opp view checks are made. if errors would come up a flash message is created and the page is redirected to the filters view.
resolves issue #195

### CODE REVIEW

**Comment by rylandbell** [comment]
Looks good. (Nice Bootstrappin'!)

I did find a typo in helpers.py: "Sorry, No results were founnd" should be "Sorry, No results were found."

**Comment by AdamD-2096** [comment]
where did that n come from? haha

**Comment by razzlepdx** [comment]
Found a typo for the zipcode error: "If it still does not work we appologize (your zipcode may not be supported yet)" - should be "apologize"

**Comment by AdamD-2096** [comment]
oh my gosh! all these extra letters..
i guess i was paying more attention to the code..
need to remember to check my Strings for typo's (making note)

**Comment by AdamD-2096** [comment]
that's weird it smushed my commits with that last push..

**Pull request merged**
