### PR TITLE
added a filter error landing page

### PR DESCRIPTION
**Pull request by AdamD-2096**
added a filter error landing page that handles no opp and no zip errors
added a little bootstrap but not much. good be greatly improved.
but here is a start.
maybe a good background image would be nice as well? 
references issue #149

### CODE REVIEW

**Comment by hendricksonsarahl** [comment]
Good thinking! We definitely need error handling messages, though the last time we discussed ideas for it I thought we planned to try flash messages in-page? That way the user can get feedback and make changes all in one place. Open to discussing the best way to handle these

**Comment by AdamD-2096** [comment]
oh.. i didn't hear about that..
and there is still an issue open for this. #149
the way i read it seems like a separate page.. 
but that is a good idea, especially for filters..
i can close this pull request and make a new issue and remove the old issue if you like.

**Comment by AdamD-2096** [comment]
i'll just do that..
wasted work is worth it for a better solution

**Comment by hendricksonsarahl** [comment]
Awesome, thanks Adam! I think it was mentioned in passing during interview night, totally forgot to make a specific issue afterwards. Sounds like a good plan to me!

**Pull request closed without merging**
