### PR TITLE
org side now uses signed in org (no more hard coded ids)

### PR DESCRIPTION
**Pull request by AdamD-2096**
i set up a function to grab an organization from a token and implemented it to root out all hard coded ids.
i tested everything that i could think of and it is working :) 
closes issue #170

### CODE REVIEW

**Comment by hendricksonsarahl** [comment]
Looks awesome! Nicely done!

**Comment by rylandbell** [comment]
@razzlepdx : I think we were typing very similar comments at the same time (great minds think alike!) To clarify: in order to get the Heroku version working, I changed the Opportunity model's foreign key to `userid`, which is now the case for both the local and Heroku versions of the app.

**Comment by hendricksonsarahl** [comment]
@AdamD-2096 Once you make the changes they suggested, you'll also have to update the version since other PRs have merged :)

**Comment by AdamD-2096** [comment]
ok. when i was creating it the userid wasn't working. but now the foreign key is userid?
and sorry i don't know anything about what Heroku needs.

i think i understand though.

**Comment by AdamD-2096** [comment]
was the userid thing changed a while ago? if so i didn't know, and i just hadn't done a drop create before working.

**Comment by AdamD-2096** [comment]
ok.
anyone want to double check one more time?

**Pull request merged**
