### PR TITLE
Created / added new design assets

### PR DESCRIPTION
**Pull request by hendricksonsarahl**
Created a custom splash page image and added some matching icons! Will use these images in index and /org/login. This relates to issues #174 and #176 .

### CODE REVIEW

**Comment by AdamD-2096** [comment]
its funny how they have that one hand different...
how did you get that voluntr image? if its custom created is there a way to make it more diverse??
i always hated how on tv they randomly started to add the ONE black guy to make there thing less subjective/"racist" but its like how does having one person who's different from all of the other cast members make it more realistic, or equal?
sorry little ranty..
its just if you're going to put in any effort to make you show more diverse.. why not make it show a piece of the whole world, and not have any of them sorely and obviously outnumbered by another..
(but at the same time from the way i see it there is no difference in people from one place or another and every single individual is unique so if everyone saw it like that no one would even think about whether a show is "uneven" and so the likelihood would be that it would be even (in its own (good) way))

gosh.. after i look back i think.. should i even send this long rant..
but at the same time i'm like.. well i already typed it all out..  lol

**Comment by AdamD-2096** [comment]
other than that 👍

**Comment by hendricksonsarahl** [comment]
I took stock images of people holding up letters and spelled out the word and there weren't any of this photo series that had the letters we needed with a more diverse ethnicity set. Changing the skin tone from this picture to something natural looking is unfortunately beyond my skills with editing software. Everything I have tried ends up looking really weird. I can try to look around some more to see if I can do anything about it at this stage, but here's my idea for the future:

I wanted to see if everyone liked this design as a concept and use this in the meantime while we finish up the core of the apps functions. Once we are ready to really deploy this, I would want to take a real custom photo recreating our own version of this. Using and changing stock photos of any kind for our live assets isn't good - we should own everything and have full rights to it. Whether that's paying a service for the assets or taking photos ourselves is up to us at that point. But no matter how much time I sink into this, it's not going to be a permanent fixture.

**Comment by AdamD-2096** [comment]
sounds :octocat: to me

**Pull request merged**
