### PR TITLE
add test_setup for imports in tests

### PR DESCRIPTION
**Pull request by rylandbell**
I've been running into error messages when I try to import functions into the files that will test them. I followed the advice in [this stackoverflow post](https://stackoverflow.com/a/47188103/8781607), which seems to have solved the problem.

### CODE REVIEW

**Comment by rylandbell** [comment]
We don't necessarily need to merge this PR, and I'm open to alternative solutions. This may be a case where my lack of Python experience is showing.

**Comment by rylandbell** [comment]
This is the error message of I've been encountering:

```ImportError while importing test module '/Users/ryland/Dropbox/webdev/projects/voluntr/tests/pytest/test_readable_date.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/pytest/test_readable_date.py:1: in <module>
    from helpers.datetime_helpers import *
E   ModuleNotFoundError: No module named 'helpers.datetime_helpers'
```

**Comment by AdamD-2096** [comment]
yes this is the same issue i've run into.
this is a good way to handle it.
i've seen two main ways to handle it each with their pros and cons.
there is this one you use. and another one that uses some sort of -m flag and a package system that i haven't wrapped my head all the way around yet.

**Comment by AdamD-2096** [comment]
i like the way he set it up so you only have to do it once.
the other way i saw was very similar, but you would have to do it in every file and it achieves basically the same thing.

**Review by AdamD-2096 — APPROVED** [review]

**Review by razzlepdx — APPROVED** [review]

**Pull request merged**
