### PR TITLE
fixed bug #110

### PR DESCRIPTION
**Pull request by AdamD-2096**
fixed bug #110

### CODE REVIEW

**Comment by rylandbell** [comment]
In `helpers.py`, why did you capitalize the "w" in "with"? It looks like it is not capitalized in the CSV file. @AdamD-2096

**Comment by hendricksonsarahl** [comment]
Looks like for some weird reason, all CSV category words need to be capitalized? "with" wasn't coming through right?

**Comment by AdamD-2096** [comment]
basically when it was looking for matches the thing it received for comparison was capital. so i just made them match.

**Comment by AdamD-2096** [comment]
ok i see... i found where it was getting the capital W since you asked. 
i could change them both to lowercase.

**Comment by AdamD-2096** [comment]
it was capital in the voluntr file where it passes in a list of categories.
i can update that along with the next PR

**Pull request closed without merging**
