### PR TITLE
Filters object re-created simple with index check

### PR DESCRIPTION
**Pull request by AdamD-2096**
not connected to anything yet, and i think i'll need some post routes created before i can. (i need to create the filter object in the filters post route and pass it around from their) any thoughts?

### CODE REVIEW

**Comment by AdamD-2096** [comment]
would close issue #54 #55

**Comment by rylandbell** [comment]
I think the line `if len(opps) > self.index:` should be `if len(opps) > self.index + 1:`, since list indexes start at 0. i.e., if the length is 5 and the index is 4, we don't want to increase the index to 5.

**Comment by rylandbell** [comment]
What is the type of the `category` variable? Is it a string or an object (or something else)?

**Comment by rylandbell** [comment]
In general, this seems like a slick way to implement filters and searching. Very OOP!

**Comment by AdamD-2096** [comment]
the category field is a string. yes.

**Comment by AdamD-2096** [comment]
i fixed the index (was missing +1)
thanks for the reminder!

**Comment by hendricksonsarahl** [comment]
This looks great! Definitely seems like a minor version update is in order too if you haven't already done so for this one 🙂

**Pull request merged**
