### PR TITLE
 view single match works

### PR DESCRIPTION
**Pull request by AdamD-2096**
view button on matches view submits a hidden opp id to post route which fetches the opp via a query and puts it into a single opp view very similar to our other opp view, but instead of save filters next buttons there is a back button 
closes issue #107

### CODE REVIEW

**Comment by AdamD-2096** [comment]
P.s. @rylandbell  you might like to fix the alignment of the view and remove buttons on the matches view.
they are now stacked on top of each other on the right side instead of side by side.
(maybe you could show me why and how to fix)

**Comment by rylandbell** [comment]
To fix the button alignment issue, you can just move the second button (the one with an `a` tag) inside the form tag.

**Comment by rylandbell** [comment]
Can we move the view page to a different route? It seems confusing to me that it doesn't change the URL in the address bar when we switch between the list of saved opps and an individual saved opp. I also check the current path in the JavaScript to decide which parts of the script to run, so the JS is currently throwing an error when the user visits a single-opp view page. I'm open to suggestions for the name of that route, but maybe `/match`? or `/match/:oppId`?

**Comment by AdamD-2096** [comment]
yea, sure.
on it

**Comment by AdamD-2096** [comment]
done

**Pull request merged**
