### PR TITLE
Calculated current version, added to README.md

### PR DESCRIPTION
**Pull request by hendricksonsarahl**
Including the two open PR requests #46 and #49:

Current Version: 0.11.2

patch: #25, #45

minor: #12, #13, #19, #28, #29, #43, #44, #45, #47, #46, #49

major:

Added to README.md at the top of the page so that we can make quick edits to that number as the version updates with future PR's.

### CODE REVIEW

**Comment by hendricksonsarahl** [comment]
This resolves issue #48

**Comment by rylandbell** [comment]
I believe that with semantic versioning, incrementing the minor version number should reset the patch number to 0. This means that we are at version 0.11.0.

For example:
Since we were at 0.3.0 when patch #25 was added, our version number went from 0.3.0 -> 0.3.1. Once minor update #28 was added, the version number went from 0.3.1 -> 0.4.0.

**Comment by rylandbell** [comment]
(See rule 7 at [semver.org](semver.og)

**Comment by razzlepdx** [comment]
Good call, @rylandbell !  Thanks for including the rule too.  I am starting to wrap my head around this concept a little better now that I'm seeing it implemented.  Thanks for listing all of the pertinent changes @hendricksonsarahl.

**Pull request merged**
